/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_emotibot_jni_JNICaller */

#ifndef _Included_com_emotibot_jni_JNICaller
#define _Included_com_emotibot_jni_JNICaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_emotibot_jni_JNICaller
 * Method:    getMultiPatternMatching
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_emotibot_jni_JNICaller_getMultiPatternMatching
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
